// Courses
export const LOAD_COURSES_SUCCESS = 'LOAD_COURSES_SUCCESS';
export const UPDATE_COURSE_SUCCESS = 'UPDATE_COURSE_SUCCESS';
export const CREATE_COURSE_SUCCESS = 'SAVE_COURSE_SUCCESS';

// Authors
export const LOAD_AUTHORS_SUCCESS = 'LOAD_AUTHORS_SUCCESS';
